import { SdkResponse } from "@huaweicloud/huaweicloud-sdk-core/SdkResponse";
export declare class CreateReleaseResponse extends SdkResponse {
    private 'chart_name'?;
    private 'chart_public'?;
    private 'chart_version'?;
    private 'cluster_id'?;
    private 'cluster_name'?;
    private 'create_at'?;
    description?: string;
    name?: string;
    namespace?: string;
    parameters?: string;
    resources?: string;
    status?: string;
    private 'status_description'?;
    private 'update_at'?;
    values?: string;
    version?: number;
    constructor();
    withChartName(chartName: string): CreateReleaseResponse;
    set chartName(chartName: string | undefined);
    get chartName(): string | undefined;
    withChartPublic(chartPublic: boolean): CreateReleaseResponse;
    set chartPublic(chartPublic: boolean | undefined);
    get chartPublic(): boolean | undefined;
    withChartVersion(chartVersion: string): CreateReleaseResponse;
    set chartVersion(chartVersion: string | undefined);
    get chartVersion(): string | undefined;
    withClusterId(clusterId: string): CreateReleaseResponse;
    set clusterId(clusterId: string | undefined);
    get clusterId(): string | undefined;
    withClusterName(clusterName: string): CreateReleaseResponse;
    set clusterName(clusterName: string | undefined);
    get clusterName(): string | undefined;
    withCreateAt(createAt: string): CreateReleaseResponse;
    set createAt(createAt: string | undefined);
    get createAt(): string | undefined;
    withDescription(description: string): CreateReleaseResponse;
    withName(name: string): CreateReleaseResponse;
    withNamespace(namespace: string): CreateReleaseResponse;
    withParameters(parameters: string): CreateReleaseResponse;
    withResources(resources: string): CreateReleaseResponse;
    withStatus(status: string): CreateReleaseResponse;
    withStatusDescription(statusDescription: string): CreateReleaseResponse;
    set statusDescription(statusDescription: string | undefined);
    get statusDescription(): string | undefined;
    withUpdateAt(updateAt: string): CreateReleaseResponse;
    set updateAt(updateAt: string | undefined);
    get updateAt(): string | undefined;
    withValues(values: string): CreateReleaseResponse;
    withVersion(version: number): CreateReleaseResponse;
}
//# sourceMappingURL=CreateReleaseResponse.d.ts.map