export declare class NodeExtendParam {
    private 'ecs:performancetype'?;
    orderID?: string;
    productID?: string;
    maxPods?: number;
    periodType?: string;
    periodNum?: number;
    isAutoRenew?: string;
    isAutoPay?: string;
    private 'DockerLVMConfigOverride'?;
    dockerBaseSize?: number;
    publicKey?: string;
    private 'alpha.cce/preInstall'?;
    private 'alpha.cce/postInstall'?;
    private 'alpha.cce/NodeImageID'?;
    nicMultiqueue?: string;
    nicThreshold?: string;
    chargingMode?: number;
    private 'agency_name'?;
    kubeReservedMem?: number;
    systemReservedMem?: number;
    private 'init-node-password'?;
    constructor();
    withEcsPerformancetype(ecsPerformancetype: string): NodeExtendParam;
    set ecsPerformancetype(ecsPerformancetype: string | undefined);
    get ecsPerformancetype(): string | undefined;
    withOrderID(orderID: string): NodeExtendParam;
    withProductID(productID: string): NodeExtendParam;
    withMaxPods(maxPods: number): NodeExtendParam;
    withPeriodType(periodType: string): NodeExtendParam;
    withPeriodNum(periodNum: number): NodeExtendParam;
    withIsAutoRenew(isAutoRenew: string): NodeExtendParam;
    withIsAutoPay(isAutoPay: string): NodeExtendParam;
    withDockerLVMConfigOverride(dockerLVMConfigOverride: string): NodeExtendParam;
    set dockerLVMConfigOverride(dockerLVMConfigOverride: string | undefined);
    get dockerLVMConfigOverride(): string | undefined;
    withDockerBaseSize(dockerBaseSize: number): NodeExtendParam;
    withPublicKey(publicKey: string): NodeExtendParam;
    withAlphaCcePreInstall(alphaCcePreInstall: string): NodeExtendParam;
    set alphaCcePreInstall(alphaCcePreInstall: string | undefined);
    get alphaCcePreInstall(): string | undefined;
    withAlphaCcePostInstall(alphaCcePostInstall: string): NodeExtendParam;
    set alphaCcePostInstall(alphaCcePostInstall: string | undefined);
    get alphaCcePostInstall(): string | undefined;
    withAlphaCceNodeImageID(alphaCceNodeImageID: string): NodeExtendParam;
    set alphaCceNodeImageID(alphaCceNodeImageID: string | undefined);
    get alphaCceNodeImageID(): string | undefined;
    withNicMultiqueue(nicMultiqueue: string): NodeExtendParam;
    withNicThreshold(nicThreshold: string): NodeExtendParam;
    withChargingMode(chargingMode: number): NodeExtendParam;
    withAgencyName(agencyName: string): NodeExtendParam;
    set agencyName(agencyName: string | undefined);
    get agencyName(): string | undefined;
    withKubeReservedMem(kubeReservedMem: number): NodeExtendParam;
    withSystemReservedMem(systemReservedMem: number): NodeExtendParam;
    withInitNodePassword(initNodePassword: string): NodeExtendParam;
    set initNodePassword(initNodePassword: string | undefined);
    get initNodePassword(): string | undefined;
}
//# sourceMappingURL=NodeExtendParam.d.ts.map